"""add DELIVERED, REFUNDED, FAILED to OrderStatus

Revision ID: 7d5ca47d93c2
Revises: f6fc4dc9f484
Create Date: 2026-03-20 16:12:03.788768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5ca47d93c2'
down_revision: Union[str, Sequence[str], None] = 'f6fc4dc9f484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
