"""add invoices and invoice_items tables

Revision ID: c388bb72e646
Revises: 7d5ca47d93c2
Create Date: 2026-03-25 22:22:53.719915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c388bb72e646'
down_revision: Union[str, Sequence[str], None] = '7d5ca47d93c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
